baseURL = "https://mihinn.github.io/blog/"
title = "Melk0revsHere"
languageCode = "en"
defaultContentLanguage = "en"

# this will be included in the footer after the current year the site is last
# built, followed by the (c) symbol
# you can use markdown inside this field
copyright = "Mihin Nimnaka"

paginate = 5  # number of articles per page in the index
summaryLength = 70  # number of words for article summaries


[params]
    author = "Mihin Nimnaka"
    description = "Hi, I am Mihin, a 23 year old information security student from Sri Lanka. And studying at NSBM Green University. Currently I am working on my personal projects and I hope to bring those stuff in the near future."  # this will be added as metadata

    posts = "posts"  # content directory where to find home page posts; default searches in "posts" and "post"
    showPostsLink = true   # show or hide the link to the simple post list
    extraContentDirs = []  # other content directories to render similarly to the home page
    showcaseDir = "showcase"  # create a content directory that shows a special showcase section in the home page

    # shows a specified single page as a home page, instead of the traditional articles list
    # requires setting `homeSinglePage`
    # goes well with extraContentDirs
    showSinglePageAsHome = false
    homeSinglePage = "/blog"

    # It's best to put these icons in the "static" folder of your site
    logo = "https://raw.githubusercontent.com/mihinN/blog/main/fav.png"
    favicon = "https://raw.githubusercontent.com/mihinN/blog/main/fav.png"  # 32x32
    faviconIco = "https://raw.githubusercontent.com/mihinN/blog/main/fav.png"  # 32x32
    appletouch = "fav.png"  # 180x180
    svgicon = "fav.ico"
    icon512 = "fav.png"  # 512x512 png image

    logoRightOfTitle = true  # positions the logo to the right of the title; default: false

    showTags = true  # show the Tags menu item; default true
    showRss = true  # show the link for the RSS feed; default true

    imageInArticlePreview = true  # show images in article preview; default false
    fitImageInArticlePreview = true  # make article preview images fit the article preview instead of getting cropped
    articleSummary = true  # show a summary in article preview; default true
    
    fontFamily = "JetBrains Mono"  # changes the font, default "JetBrains Mono"
    titleFontFamily = "JetBrains Mono"  # font used for titles and headings
    monospaceFontFamily = "JetBrains Mono"  # changes the monospace font for code, default "JetBrains Mono"

    # multipliers applied to font sizes, useful for custom fonts that may be too big or too small
    titleFontSizeMultiplier = 1.0
    mainFontSizeMultiplier = 1.0
    monoFontSizeMultiplier = 1.0

    contentWidth = "1000px"  # maximum width of the site content, css syntax

    paperCards = true  # enable paper card style; default false
    buttonTags = true  # enable button tag style; default false
    tagsInArticlePreview = true  # enable tags list in the article preview card
    gridView = true  # show post list as a grid. goes well with paperCards
    bigArticleTitle = false  # makes the title in the single article view bigger
    navtype = "standard"  # changes the style of the pagination, available styles are: "standard", "circles"
    enableShadow = true  # shows a shadow around some elements
    menuStyle = "standard"  # changes the style of the main site navigation menu, available styles are: "standard", "buttons"
    inputStyle = "buttons" # changes the style of inputs (like the searchbar), available styles are: "standard", "buttons"

    enableSearch = false  # enable search page
    searchbarEverywhere = true  # if the searchbar should be shown in every page; requires enableSearch
    searchMenuLink = false  # add a search link to the navigation menu; requires enableSearch
    mobileHamburgerNav = true  # alternative hamburger menu layout for the main nav menu when screen is small

    enableFeatured = false  # enable a particular view for articles marked as featured (featured: true in the article frontmatter)

    underlineTitleLinks = false  # show an underline also for links that are titles



    enableShareOnFediverse = true  # enable a button at the end of an article to share it on the fediverse
    tocBeforeImage = false  # show the table of contents before the main article image; default false

    # WARNING: deprecated! Use [[menu.icons]] instead, look below
    # links = [
    #     ["GitLab", "https://gitlab.com/gabmus"],
    #     ["GNOME", "https://gitlab.gnome.org/gabmus"],
    #     ["YouTube", "https://youtube.com/TechPillsNet"]
    # ]

    # you can customize all of the colors in this theme
    # Colors are defined in data/colors.yml

    # alternative sidebar layout
    enableSidebarLayout = false
    tocInSidebar = false  # if the sidebar is enbabled, show the TOC in the sidebar

    # redirect to baseURL if current URL host doesn't match
    # useful if deploying in gitlab pages with custom domain and don't want
    # the username.gitlab.io/website url to persist
    # this requires you to set baseURL (see above)
    forceRedirect = true

    infiniteScrolling = false  # activates infinite scrolling instead of regular pagination
    enableFooterColumns = true  # activates footer columns, as described below
    enableJumbotron = false  # enables jumbotron, as described below
    # related articles will be selected randomly based on tags and shown at
    # the bottom of the article, after the comments
    enableRelatedArticles = false
    relatedArticlesNum = 2  # how many related articles to show
    randomRelated = false  # sorts related articles in random order (randomized at built time)

[menu]
    # these links will be added to the main navigation menu, sorted by weight
    # other elements in this menu are added automatically from the "pages" folder
    # the folder it will look into can be customized with the pages variable
    # in params above
    [[menu.main]]
        identifier = "whoami"
        name = "whoami"
        url = "/whoami"
        weight = 2

    [[menu.main]]
        identifier = "c_tuts"
        name = "C lessons"
        url = "/c_tuts"
        weight = 10
    
    [[menu.main]]
        identifier = "networking_tuts"
        name = "networking Lessons"
        url = "/networking_tuts"
        weight = 10

     [[menu.main]]
        identifier = "other"
        name = "other"
        url = "/other"
        weight = 10

        
    # these links (menu.icons) will be added as icon links below the main nav
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/mihinN"
        weight = 10

# this section is necessary if you want infinite scrolling
# it allows to output the article list as paged JSON so that "pages" can be retrieved via javascript
[outputs]
    home = ["HTML", "JSON",]

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1

