baseURL = "https://mihiN.github.io/blog/"
languageCode = 'en-us'
title = '0xMelK0reWa5Here'


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]

  colortheme = "dark" # dark, light, white, or classic
  css = ["css/custom.css"]
  description = "Hey ! Welcome to My Webpage , I will update soon and there will be a lot here (tutorials , tech writings , projects and upcoming projects ), so thanks for stopping by!"
  mainSection = "posts"
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  tagsOverview = true
  tocInline = true
  showProjectsList = true
  projectsUrl = ""

  [[params.social]]
  name = "github"
  link = "https://github.com/mihinN"

[[params.social]]
  name = "email"
  link = "" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "www.linkedin.com/in/mihin-nimnaka"

  copyright = "Mihin Nimnaka" # cactus theme will use site title if copyright is not set


  [params.comments]
    enabled = false
    # engine = "disqus" # in progress

    [markup]
    [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

    rss = true
    mathjax = true  # not required
    showAllPostsArchive = true # or false (default)